06) Single Sign-On/SingleSignOn/Models/DataTransferObjects/IdTokenVerificationRequest.cs
namespace SingleSignOn.Models.DataTransferObjects
{
    public class IdTokenVerificationRequest
    {
        public string IdToken { get; set; }
    }
}

06) Single Sign-On/SingleSignOn/Models/ErrorViewModel.cs
using System;

namespace SingleSignOn.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

06) Single Sign-On/SingleSignOn/Models/User.cs
using System;
using Microsoft.AspNetCore.Identity;

namespace SingleSignOn.Models
{
    public class User : IdentityUser<Guid>
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

06) Single Sign-On/SingleSignOn/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SingleSignOn.Models;

namespace SingleSignOn.Controllers
{
    public class HomeController : Controller
    {
        /**
         * WELCOME page
         * Upon application start, this action will be called.
         */
        public IActionResult Index()
        {
            return View();
        }

        /**
         * Displays the login page.
         * Add the single sign-on authentication buttons in the view related to this action.
         */
        public IActionResult Login()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

06) Single Sign-On/SingleSignOn/Controllers/ProfileController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SingleSignOn.Models;

namespace SingleSignOn.Controllers
{
    public class ProfileController : Controller
    {
        /**
         * The user manager is a handy tool for various operations regarding User objects.
         * It might be used to create and/or retrieve users.
         */
        private readonly UserManager<User> _userManager;

        /**
         * Constructor of the ProfileController.
         * The userManager dependency is provided by dependency injection.
         */
        public ProfileController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        /**
         * Displays the users profile data.
         * The Authorize attribute protects this action: Only authenticated user may call it.
         */
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            ViewBag.User = user;
            return View();
        }

        /**
         * Logout handler - ends the currently authenticated users session.
         */
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }
    }
}

06) Single Sign-On/SingleSignOn/Controllers/UserController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Google.Apis.Auth;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SingleSignOn.Data;
using SingleSignOn.Models;
using SingleSignOn.Models.DataTransferObjects;
using SingleSignOn.Services;

namespace SingleSignOn.Controllers
{
    public class UserController : Controller
    {
        /**
         * The user manager is a handy tool for various operations regarding User objects.
         * It might be used to create and/or retrieve users.
         */
        private readonly UserManager<User> _userManager;

        /**
         * Constructor of the UserController.
         * The userManager dependency is provided by dependency injection.
         */
        public UserController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        /**
         * This action is used for verification of the provided id token.
         * If the token is valid, an existing user with the validated user data is retrieved from the user store (using the _userManager).
         * If no user with the validated user data exists, a new user object is created and added to the user user store.
         *
         * Finally, the (existing|created) user gets authenticated and a http status 200 (Ok) is returned.
         *
         * If the validation of the id token with the identity providers backend fails, a http status 400 (BadRequest) is returned.
         */
        [HttpPost]
        public async Task<IActionResult> VerifyIdToken([FromBody] IdTokenVerificationRequest verificationRequest)
        {
            // TODO: Implement this method according to the above comment.
            try
            {
                GoogleJsonWebSignature.Payload payload = GoogleJsonWebSignature.ValidateAsync(verificationRequest.IdToken).Result;
                if (payload.EmailVerified)
                {
                    User user = _userManager.Users.FirstOrDefault(x => x.Email == payload.Email && x.FirstName == payload.GivenName);
                    if (user != null)
                    {
                        await AuthenticateUser(user);

                        return Ok();
                    }
                    else
                    {
                        User newUser = await CreateUser(payload.Email, payload.GivenName, payload.FamilyName);
                        await AuthenticateUser(newUser);

                        return Ok();
                    }
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        /**
         * Creates a new user object with the given data and adds it to the user store.
         * If the creation and persistence of the user object succeeded, the user object is returned. In case of failure, null is returned.
         */
        private async Task<User> CreateUser(string email, string firstName, string lastName)
        {
            var user = new User
            {
                UserName = email,
                Email = email,
                FirstName = firstName,
                LastName = lastName,
            };
            var result = await _userManager.CreateAsync(user);

            return result.Succeeded ? user : null;
        }

        /**
         * Authenticates the given user object using the cooke authentication scheme.
         * The cookie (and therefore the session) will last for 1 day.
         */
        private async Task AuthenticateUser(User user)
        {
            var authProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                IsPersistent = true,
                ExpiresUtc = DateTimeOffset.Now.AddDays(1),
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(UserService.CreateClaimsIdentity(user)),
                authProperties
            );
        }
    }
}

06) Single Sign-On/SingleSignOn/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <div class="container">
        <div class="row">
            <div class="col">
                <p>Welcome on this little demo application.</p>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p>Head over to <a asp-action="Login">Login</a> to login using a single sign-on provider.</p>
            </div>
        </div>
    </div>
</div>

06) Single Sign-On/SingleSignOn/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

@section Scripts
{
    <!-- Include Google Platform Library -->
    <script src="https://apis.google.com/js/platform.js"></script>

    <script src="~/js/googleSignIn.js" asp-append-version="true"></script>
}

<div class="text-center">
    <h1 class="display-4">Login</h1>

    <div class="container">
        <div class="row">
            <p>
                Use one of the options below to sign-in with an existing user account you already have.<br/>
                You are not required to sign-up for this application. Instead, it will just use your identity provided by the chosen authentication service.
            </p>
        </div>
        <div class="row">
            <div class="col">

                <!--
                This is the google sign-in button.
                TODO: You might want to start implementing the onSuccess javascript function in the corresponding javascript file...
                -->
                <div class="g-signin2 mt-5" data-onsuccess="onSuccess"></div>

            </div>
        </div>
    </div>
</div>

06) Single Sign-On/SingleSignOn/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.Extensions.Configuration
@using Microsoft.AspNetCore.Identity
@inject IConfiguration Configuration
@inject SignInManager<User> SignInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="google-signin-client_id" content="@Configuration["SSO:Google:ClientId"]">
    <title>@ViewData["Title"] - SingleSignOn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SingleSignOn</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Peter Gisler
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
@RenderSection("Scripts", required: false)
</body>
</html>